package com.project.settings;

public class GithubLogin {

	// This token is generated by Go to your github account Settings > Developer
	// Settings > Personal Access Tokens, add token here
	public static String userName = "9be395b1cf41316337f993763bb891d02fcf9e9c";

}
